---
title: "Publications"
---

## 2024

- Bertolet, B. L., **Chavez Rodriguez L.**, Murúa, J. M., Favela, A., & Allison, S. D. (2024). The Impact of Microbial Interactions on Ecosystem Function Intensifies Under Stress. Ecology Letters, 27(10), e14528. https://doi.org/10.1111/ele.14528

- Anthony, W. E., Allison, S. D., Broderick, C. M., **Chavez Rodriguez L.**, Clum, A., Cross, H., Eloe-Fadrosh, E., Evans, S., Fairbanks, D., Gallery, R., Gontijo, J. B., Jones, J., McDermott, J., Pett-Ridge, J., Record, S., Rodrigues, J. L. M., Rodriguez-Reillo, W., Shek, K. L., Takacs-Vesbach, T., & Blanchard, J. L. (2024). From soil to sequence: filling the critical gap in genome-resolved metagenomics is essential to the future of soil microbial ecology. Environmental Microbiome, 19(1), 56. https://doi.org/10.1186/s40793-024-00599-w

- Duan, E. S., **Chavez Rodriguez L.**., Hemming-Schroeder, N., Wijas, B., Flores-Moreno, H., Cheesman, A. W., Cernusak, L. A., Liddell, M. J., Eggleton, P., Zanne, A. E., and Allison, S. D. (2024). Climate-based prediction of carbon fluxes from deadwood in Australia, Biogeosciences, 21, 3321–3338, https://doi.org/10.5194/bg-21-3321-2024.

- Wijas, B. J., Flores-Moreno, H., Allison, S. D., **Chavez Rodriguez L.**., Cheesman, A. W., Cernusak, L. A., Clement, R., Cornwell, W. K., Duan, E. S., Eggleton, P., Rosenfield, M. V., Yatsko, A. R., & Zanne, A. E. (2024). Drivers of wood decay in tropical ecosystems: Termites versus microbes along spatial, temporal and experimental precipitation gradients. Functional Ecology. https://doi.org/10.1111/1365-2435.14494

## 2023

- Wirsching J., **Chavez Rodriguez L.**, Ditterich R., Pagel H., He R., Uksa M., Zwiener C., Kandeler E., Poll C. (2023). Temperature and soil moisture change microbial allocation of pesticide-derived carbon. European Journal of Soil Science. https://doi.org/10.1111/ejss.13417

- **Chavez Rodriguez L.**., Parker, Scot., Fiore Nicole M., Allison, Steven D., Goulden, Michael L. (2023). Impact of drought on ecohydrology of Southern California grassland and shrubland. Ecosystems. https://doi.org/10.1007/s10021-023-00876-8

## 2022

- Schwarz, E., Khurana, S., Chakrawal, A., **Chavez Rodriguez, L.**, Wirsching, J., Streck, T., Manzoni, S., Thullner, M., & Pagel, H. (2022). Spatial Control of Microbial Pesticide Degradation in Soil: A Model-Based Scenario Analysis. Environmental Science & Technology, 56(20), 14427–14438. https://doi.org/10.1021/acs.est.2c03397

- **Chavez Rodriguez, L.**, Gonzalez-Nicolas, A., Ingalls, B., Streck, T., Nowak, W., Xiao, S., & Pagel, H. (2022). Optimal design of experiments to improve the characterisation of atrazine degradation pathways in soil. European Journal of Soil Science, 73(1). https://doi.org/10.1111/ejss.13211

## 2021

- **Chavez Rodriguez, L.**, Ingalls, B., Meierdierks, J., Kundu, K., Streck, T., & Pagel, H. (2021). Modeling Bioavailability Limitations of Atrazine Degradation in Soils. Frontiers in Environmental Science, 9, 706457. https://doi.org/10.3389/fenvs.2021.706457

## 2020

- **Chavez Rodriguez, L.**, Ingalls, B., Schwarz, E., Streck, T., Uksa, M., & Pagel, H. (2020). Gene-Centric Model Approaches for Accurate Prediction of Pesticide Biodegradation in Soils. Environmental Science & Technology, 54(21), 13638–13650. https://doi.org/10.1021/acs.est.0c03315

